# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='abstract',
            field=models.CharField(blank=True, max_length=250, verbose_name='摘要'),
        ),
    ]
